[package]
name = "eqld"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eql-core = { path = "../eql-core" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
toml = "0.8"
