[package]
name = "eqls"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eql-core = { path = "../eql-core" }
axum = "0.8"
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "migrate", "time"] }
thiserror = { workspace = true }
time = { version = "0.3", features = ["formatting", "parsing", "serde-well-known"] }
tokio = { workspace = true }
tower-http = { version = "0.6", features = ["fs"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
